##############################
### WINDOWS AND WORKSPACES ###
##############################

# Boot Programs
windowrule = workspace 5, match:class ^(discord)$

# General Rules
windowrule = suppress_event maximize, match:class .*

# XWayland Dragging Fix
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# JetBrains IDE Fixes
windowrule = tag +jb, match:class ^jetbrains-.+$, match:float 1
windowrule = stay_focused on, no_initial_focus on, match:tag jb
windowrule = tag +jb, match:class ^jetbrains-.+$, match:float 1, match:title ^(?!win\d+$).*
windowrule = no_focus on, no_initial_focus on, match:class ^jetbrains-.+$, match:title ^win\d+$
